#!/bin/bash
echo "Setting up a new, awesome project"

Project=$1
Destination=$2
SkeletonDirname=`dirname $0`
PathToProject=$(cd $SkeletonDirname/$Project; pwd)

if [ -d $Destination ]; then
  echo "$Destination already exists. Aborting."
  exit
fi

cp -r $PathToProject $Destination

pushd $Destination

source "$PathToProject/setup.sh"

rm setup.sh

popd

echo "Complete!"
