#!/bin/bash
echo "Setting up a new, awesome project"

Project=$1
Destination=$2
SkeletonDirname=`dirname $0`
PathToProject=$(cd $SkeletonDirname/$Project; pwd)

cp -r $PathToProject $Destination

pushd $Destination

source "$PathToProject/setup.sh"

rm setup.sh

popd

echo "Complete!"
